#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/tags.$$"' EXIT INT TERM
{ git ls-files; git-ls-files -o; } | \
  ctags --tag-relative=yes -L - -f$dir/tags.$$ --languages=-javascript,sql
mv $dir/tags.$$ $dir/tags
